/* do not change this file, it is auto generated by storybook. */
import { start, updateView, type View } from "@storybook/react-native";

import "@storybook/addon-ondevice-actions/register";
import "@storybook/addon-ondevice-controls/register";

const normalizedStories = [
	{
		titlePrefix: "",
		directory: "./components",
		files: "**/*.stories.?(ts|tsx|js|jsx)",
		importPathMatcher:
			/^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
		req: require.context(
			"../components",
			true,
			/^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
		),
	},
];

declare global {
	var view: View;
	var STORIES: typeof normalizedStories;
}

const annotations = [
	require("./preview"),
	require("@storybook/react-native/preview"),
];

global.STORIES = normalizedStories;

// @ts-expect-error
module?.hot?.accept?.();

if (!global.view) {
	global.view = start({
		annotations,
		storyEntries: normalizedStories,
	});
} else {
	updateView(global.view, annotations, normalizedStories);
}

// biome-ignore lint/suspicious/noRedeclare: it's auto generated file
export const view: View = global.view;
